### ISSUE TITLE
clone.sh fails due to syntax error Ubuntu 16.04

### ISSUE THREAD

**Issue by Nikki1993** [Turbine1991/build_ubuntu_kernel_wastedcores#1]
Running sudo bash clone.sh gives

```
Picking 'linux' as source package instead of 'linux-image-4.4.0-21-generic'
E: Unable to find a source package for linux-image-4.4.0-21-generic
```

and 

```
clone.sh: line 88: syntax error near unexpected token `}'
clone.sh: line 88: `}'
```

Ubuntu 16.04, stock kernel, no mods except 2 ppa, for latest stable git and nodejs.

**Comment by Turbine1991** [comment]
Have you enabled your source repositories? I'll look into the syntax error.

**Comment by Turbine1991** [comment]
Please re-clone this repository and try again. It will now add the source entries. I've also fixed the syntax error.

**Comment by Turbine1991** [comment]
Committed.
