### ISSUE TITLE
4.10

### ISSUE THREAD

**Issue by atomi** [Turbine1991/build_ubuntu_kernel_wastedcores#10]
4.10 is released

**Comment by Turbine1991** [comment]
Acknowledged.

**Comment by atomi** [comment]
easiest way to update for a quick build:

https://github.com/Turbine1991/build_ubuntu_kernel_wastedcores/blob/master/clone.sh#L96

changed to:
`KERNEL_VERSION="4.10"` 

and make sure you're not cloning the dailys
```
  PATCH_DIR=`get_http_apache_listing "$KERNEL_SOURCE_URL" "v$KERNEL_VERSION" 1`
  PATCH_URL="$KERNEL_SOURCE_URL/$PATCH_DIR"
```

but it works

**Comment by Turbine1991** [comment]
Cheers, committing now. At some point I'll just make it retrieve all stable versions from the website itself, avoiding the need to manually introduce an entry.

**Comment by Turbine1991** [comment]
Fixed all of the versions in a commit just now.

**Comment by atomi** [comment]
Any reason you aren't using the upstream kernel?
