### ISSUE TITLE
Cannot build daily (currently 4.11-rc2)

### ISSUE THREAD

**Issue by Turbine1991** [Turbine1991/build_ubuntu_kernel_wastedcores#11]
There's two reasons for this in-order for it to clone & compile.

-The branch needs to be "master" when daily is selected.
-The file "kernel/mainline-crack/REPORTING-BUGS", has been removed despite "make-kpkg" requiring this file. I'll make it generate an empty file if necessary using "touch", as it's non-critical information.

**Comment by ghost** [comment]
I'm afraid it's not only daily, I tried current 4.9 (4.9.16) and script also cant download source.
So I waited for the moment when script asks for CPU scheduler, went to the 'kernel' folder and downloaded 'mainline_crack' manually
`sudo git clone --depth 1 --branch v4.9.13 git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack`

**Comment by Turbine1991** [comment]
Everything becomes rather volatile with all of these kernel changes. I'll have to find a more robust way to select branches correctly.

**Comment by Turbine1991** [comment]
I'm pushing a fix through now, it'll make all of the versions clone and compile properly.

It'll also fix people with missing source repository entries.
