### ISSUE TITLE
Bump kernel to 4.4

### ISSUE THREAD

**Issue by Nikki1993** [Turbine1991/build_ubuntu_kernel_wastedcores#2]
Kind of question/request, any reason to use 4.1 with patches and not use latest LTS 4.4 that is also being shipped in Ubuntu 16.04?

**Comment by Turbine1991** [comment]
The scheduling code changed in a newer kernel version, resulting in failure when patching. A few things have changed, I'll look into it again and see if such a change could be viably ported, without extensive knowledge of the workings.

**Comment by Turbine1991** [comment]
Please let me know if you have any troubles executing the script now.

**Comment by Freeaqingme** [comment]
I spent some time today compiling the patches against linux 4.5. The scheduler doesn't appear to have been touched a lot as part of 4.4, so chances are they'll apply cleanly to 4.4 as well.

https://github.com/Freeaqingme/wastedcores/tree/linux-4.5

**Comment by Turbine1991** [comment]
I'll include this as the default patch. It also works with 4.6!

**Comment by Freeaqingme** [comment]
Tnx! I revamped the README a bit and linked to this repo for everybody looking for an easy way to do it.

Fwiw, I saw this line: https://github.com/Turbine1991/build_ubuntu_kernel_wastedcores/blob/master/clone.sh#L90

I think it's safe to remove, given that I also had to include something similar in my patches to get it to work in the first place ( https://github.com/Freeaqingme/wastedcores/blob/master/patches/missing_sched_domains.patch#L9 )

**Comment by Turbine1991** [comment]
Yes, that worked perfectly. Thank you, I was not happy with my quick fix. I've linked your repository in the readme. Hopefully you don't mind me using your article excerpt.

**Comment by Freeaqingme** [comment]
That's alright. I also borrowed it :)

Anyways, this thread is about Linux 4.4. I also required a linux 4.4 build, so I backported the patches against 4.4.8 as well. They can be found here: https://github.com/Freeaqingme/wastedcores/tree/linux-4.4

**Comment by Turbine1991** [comment]
@Freeaqingme I've noticed a regression in WastedCores. While it will overall improve throughput. Performance dependant applications - such as games, tend to more variable performance. In the forms of spikes due to overscheduling. This happens in the vanilla kernel already, so they're only worsened.

**Comment by Freeaqingme** [comment]
I think that's sort of expected. The patches were made with high-contention systems in mind, where there's considerable more threads or processes than there's cores. It seems somewhat logical then that there's a downside in other situations.

Maybe some time someone could look into whether it would be possible to create some sysctl setting to switch between behavior. I don't have time to do so any time soon though.

**Comment by Turbine1991** [comment]
It's fundamentally in the logic of the scheduler, no matter the tweak applied through sysctl - I suspect.

I've made this script retrieve all your branches from your git repository and provide them as a choice to the user. It manually includes the 4.1 entry and the latest unstable version for the daring.

```
Kernel Versions
Cloning into 'temp'...
remote: Counting objects: 44, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 40
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.

Kernel Versions
1) 4.6
2) 4.5
3) 4.4
4) 4.1
Please enter your choice:
```
