### ISSUE TITLE
Give a better name than "custom" to the kernels

### ISSUE THREAD

**Issue by AXDOOMER** [Turbine1991/build_ubuntu_kernel_wastedcores#8]
It would be better to give the kernel the name of it's scheduler.

**Comment by Turbine1991** [comment]
Good idea, there's a reason to this madness though. It must boot the latest kernel no matter the configuration, the bootloader does this based on the name. I've got to keep some sort of constant numbering system. I'll append it after custom.

**Comment by AXDOOMER** [comment]
Append the name after the constant then.

Instead of `custom1`, name it `1MuQSS` or something like that. I think that would work.

**Comment by Turbine1991** [comment]
It's a bit more confusing than that, '-' and '.' are version separator operators. There's things like major and minor versioning going on.

I've added this feature, but it's "custom2-muqss". I do like having the term custom quite visible, as there's often a lot of generic kernels if people don't clear them out.

I've not tested the patch. But there's not much which could go wrong here.

**Comment by AXDOOMER** [comment]
> custom2-muqss

That's good. Thanks!
