### ISSUE TITLE
Add BFS

### ISSUE THREAD

**Issue by AXDOOMER** [Turbine1991/build_ubuntu_kernel_wastedcores#9]
I would like to compare all of them, so adding BFS would be great. MuQSS is the successor to BFS, but they are very different and don't handle the threads the same way.

http://ck.kolivas.org/patches/bfs/4.0/

**Comment by Turbine1991** [comment]
I can do this, thanks for that. It seems to stop at 4.8.

When you do the test, I recommend trying it with and without kernel pre-emption.
